### ISSUE TITLE
Partial support

### ISSUE THREAD

**Issue by marcog83** [folktale/core.lambda#4]
Hi, i'm new in functional programming, but I like it and I think that folktale is a great library!!!

this is not an issue, but a question,
My goal is coding something like this

``` javascript
function myFunction(a,b){ 
   return a+b;
}
var prefilled=partial(myFunction,1,2);

console.log(prefilled());
```

lodash or underscore have a function named "partial" and native 
Function.prototype.bind can be used too.

But I wondered if there is some reason  why "partial" is not implemented, for instance there is another way to achieve the result that I can't see.

I did a dirty version like this

``` javascript
 function partial(n,func) {
        var args = [].slice.call(arguments,2);
        var c = λ.curry(n, func);
        var k = λ.constant(args);
        var s = λ.curry(2, λ.spread)(c);
        return λ.compose(s, k);
    }

//and usage would be

var prefilled=partial(2,myFunction,5,15);

console.log(prefilled());//20
```

thanks.
FP blows my mind :)

**Comment by robotlolita** [comment]
Partial application is natural when you functions are curried. Folktale caters to the same idioms Haskell uses, so it expects that all functions you want to partially apply will be curried.

For example:

``` js
var add = curry(2, function(a, b) {
  return a + b
})
var mul = curry(2, function(a, b) {
  return a * b
})
var div = curry(2, function(a, b) {
  return a / b
})
```

Then if you want to give a name to partial applications of those functions, you just do it naturally:

``` js
var double = mul(2)
var divideByThree = flip(div)(3) // flip((a, b) => ...) = (b, a) => ...
```

Currying in Folktale enforces that function application always does the right thing too, so if you have `curriedFn(1, 2, 3)`, that's **always** the same as `curriedFn(1)(2)(3)`. This is important for functions that might return other functions:

``` js
var constant = curry(2, function(a, b) {
  return a
})

constant(add(2), add(5), 3) // => same as add(2)(3)
```

In your example, though, you only need to wrap it in another function, no need for partial:

``` js
var prefilled = function(){ return myFunction(1, 2) }
```

Note however that currying doesn't go along very well with variadic functions, so Folktale idioms avoid variadic functions for that reason.

Particularly, I only think a `partial` function is a good idea when it's either supported in the syntax (like what you have in Scala or Purr), that way you could write:

``` js
function divideBy(a, b) {
  return a / b
}
var divideBy5 = divideBy(#, 5)
// would be the same as:
// function divideBy5(a){ return a / 5 }
```

Or a similar function that does that. While it's relatively easy to implement that kind of `partial`, it has quite a bit of overhead, since you need to go through all of the arguments of the function, check if any of them is a hole, fill the holes with the provided arguments, then either create a new function or invoke the underlying one (if you allow calling the function with less arguments than it expects).

**Comment by marcog83** [comment]
Thanks a lot for this complete explanation, the more i 'm going into this world, the most I realize I miss a lot of theory. It will take some time before I could really understand your answer, but i'll not give up :)
